const MC18_ITEMS = [
  { id:1,   material:"STONE",               type:"block", textures:{0:"stone",1:"stone_granite",2:"stone_granite_smooth",3:"stone_diorite",4:"stone_diorite_smooth",5:"stone_andesite",6:"stone_andesite_smooth"} },
  { id:2,   material:"GRASS",               type:"block", textures:{0:"grass_side"} },
  { id:3,   material:"DIRT",                type:"block", textures:{0:"dirt",1:"coarse_dirt",2:"dirt_podzol_side"} },
  { id:4,   material:"COBBLESTONE",         type:"block", textures:{0:"cobblestone"} },
  { id:5,   material:"WOOD",                type:"block", textures:{0:"planks_oak",1:"planks_spruce",2:"planks_birch",3:"planks_jungle",4:"planks_acacia",5:"planks_big_oak"} },
  { id:6,   material:"SAPLING",             type:"block", textures:{0:"sapling_oak",1:"sapling_spruce",2:"sapling_birch",3:"sapling_jungle",4:"sapling_acacia",5:"sapling_roofed_oak"} },
  { id:7,   material:"BEDROCK",           type:"block", textures:{0:"bedrock"} },
  { id:8,   material:"CACTUS",               type:"block", textures:{0:"cactus_side"} },
  { id:12,  material:"SAND",               type:"block", textures:{0:"sand",1:"red_sand"} },
  { id:13,  material:"GRAVEL",             type:"block", textures:{0:"gravel"} },
  { id:14,  material:"GOLD_ORE",          type:"block", textures:{0:"gold_ore"} },
  { id:15,  material:"IRON_ORE",           type:"block", textures:{0:"iron_ore"} },
  { id:16,  material:"COAL_ORE",            type:"block", textures:{0:"coal_ore"} },
  { id:17,  material:"LOG",                type:"block", textures:{0:"log_oak",1:"log_spruce",2:"log_birch",3:"log_jungle"} },
  { id:18,  material:"LEAVES",             type:"block", textures:{0:"leaves_oak",1:"leaves_spruce",2:"leaves_birch",3:"leaves_jungle"} },
  { id:19,  material:"SPONGE",             type:"block", textures:{0:"sponge"} },
  { id:20,  material:"GLASS",              type:"block", textures:{0:"glass"} },
  { id:21,  material:"LAPIS_ORE",          type:"block", textures:{0:"lapis_ore"} },
  { id:22,  material:"LAPIS_BLOCK",        type:"block", textures:{0:"lapis_block"} },
  { id:24,  material:"SANDSTONE",          type:"block", textures:{0:"sandstone_normal",1:"sandstone_chiseled",2:"sandstone_smooth"} },
  { id:25,  material:"NOTE_BLOCK",         type:"block", textures:{0:"noteblock"} },
  { id:35,  material:"WOOL",               type:"block", textures:{0:"wool_colored_white",1:"wool_colored_orange",2:"wool_colored_magenta",3:"wool_colored_light_blue",4:"wool_colored_yellow",5:"wool_colored_lime",6:"wool_colored_pink",7:"wool_colored_gray",8:"wool_colored_silver",9:"wool_colored_cyan",10:"wool_colored_purple",11:"wool_colored_blue",12:"wool_colored_brown",13:"wool_colored_green",14:"wool_colored_red",15:"wool_colored_black"} },
  { id:37,  material:"YELLOW_FLOWER",      type:"block", textures:{0:"flower_dandelion"} },
  { id:38,  material:"RED_ROSE",           type:"block", textures:{0:"flower_rose",1:"flower_blue_orchid",2:"flower_allium",3:"flower_houstonia",4:"flower_tulip_red",5:"flower_tulip_orange",6:"flower_tulip_white",7:"flower_tulip_pink",8:"flower_oxeye_daisy"} },
  { id:41,  material:"GOLD_BLOCK",         type:"block", textures:{0:"gold_block"} },
  { id:42,  material:"IRON_BLOCK",         type:"block", textures:{0:"iron_block"} },
  { id:45,  material:"BRICK",              type:"block", textures:{0:"brick"} },
  { id:46,  material:"TNT",                type:"block", textures:{0:"tnt_side"} },
  { id:47,  material:"BOOKSHELF",          type:"block", textures:{0:"bookshelf"} },
  { id:48,  material:"MOSSY_COBBLESTONE",  type:"block", textures:{0:"cobblestone_mossy"} },
  { id:49,  material:"OBSIDIAN",           type:"block", textures:{0:"obsidian"} },
  { id:52,  material:"MOB_SPAWNER",         type:"block", textures:{0:"mob_spawner"} },
  { id:56,  material:"DIAMOND_ORE",        type:"block", textures:{0:"diamond_ore"} },
  { id:57,  material:"DIAMOND_BLOCK",      type:"block", textures:{0:"diamond_block"} },
  { id:58,  material:"WORKBENCH",          type:"block", textures:{0:"crafting_table_front"} },
  { id:61,  material:"FURNACE",            type:"block", textures:{0:"furnace_front_off"} },
  { id:73,  material:"REDSTONE_ORE",       type:"block", textures:{0:"redstone_ore"} },
  { id:79,  material:"ICE",                type:"block", textures:{0:"ice"} },
  { id:80,  material:"SNOW_BLOCK",         type:"block", textures:{0:"snow"} },
  { id:82,  material:"CLAY",                type:"block", textures:{0:"clay"} },
  { id:86,  material:"PUMPKIN",            type:"block", textures:{0:"pumpkin_face_off"} },
  { id:87,  material:"NETHERRACK",         type:"block", textures:{0:"netherrack"} },
  { id:88,  material:"SOUL_SAND",          type:"block", textures:{0:"soul_sand"} },
  { id:89,  material:"GLOWSTONE",          type:"block", textures:{0:"glowstone"} },
  { id:98,  material:"SMOOTH_BRICK",       type:"block", textures:{0:"stonebrick",1:"stonebrick_mossy",2:"stonebrick_cracked",3:"stonebrick_carved"} },
  { id:110, material:"MYCEL",              type:"block", textures:{0:"mycelium_side"} },
  { id:112, material:"NETHER_BRICK",       type:"block", textures:{0:"nether_brick"} },
  { id:121, material:"END_STONE",          type:"block", textures:{0:"end_stone"} },
  { id:129, material:"EMERALD_ORE",       type:"block", textures:{0:"emerald_ore"} },
  { id:133, material:"EMERALD_BLOCK",     type:"block", textures:{0:"emerald_block"} },
  { id:152, material:"REDSTONE_BLOCK",    type:"block", textures:{0:"redstone_block"} },
  { id:153, material:"QUARTZ_ORE",         type:"block", textures:{0:"quartz_ore"} },
  { id:155, material:"QUARTZ_BLOCK",       type:"block", textures:{0:"quartz_block_side",1:"quartz_block_chiseled",2:"quartz_block_lines"} },
  { id:159, material:"STAINED_CLAY",       type:"block", textures:{0:"hardened_clay_stained_white",1:"hardened_clay_stained_orange",2:"hardened_clay_stained_magenta",3:"hardened_clay_stained_light_blue",4:"hardened_clay_stained_yellow",5:"hardened_clay_stained_lime",6:"hardened_clay_stained_pink",7:"hardened_clay_stained_gray",8:"hardened_clay_stained_silver",9:"hardened_clay_stained_cyan",10:"hardened_clay_stained_purple",11:"hardened_clay_stained_blue",12:"hardened_clay_stained_brown",13:"hardened_clay_stained_green",14:"hardened_clay_stained_red",15:"hardened_clay_stained_black"} },
  { id:161, material:"LEAVES_2",            type:"block", textures:{0:"leaves_acacia",1:"leaves_big_oak"} },
  { id:162, material:"LOG_2",              type:"block", textures:{0:"log_acacia",1:"log_big_oak"} },
  { id:170, material:"HAY_BLOCK",          type:"block", textures:{0:"hay_block_side"} },
  { id:172, material:"HARD_CLAY",          type:"block", textures:{0:"hardened_clay"} },
  { id:173, material:"COAL_BLOCK",          type:"block", textures:{0:"coal_block"} },
  { id:174, material:"PACKED_ICE",          type:"block", textures:{0:"ice_packed"} },
  { id:175, material:"DOUBLE_PLANT",       type:"block", textures:{0:"double_plant_sunflower_front",1:"double_plant_syringa_top",2:"double_plant_grass_top",3:"double_plant_fern_top",4:"double_plant_rose_top",5:"double_plant_paeonia_top"} },
  { id:256, material:"IRON_SPADE",         type:"item",  textures:{0:"iron_shovel"} },
  { id:257, material:"IRON_PICKAXE",       type:"item",  textures:{0:"iron_pickaxe"} },
  { id:258, material:"IRON_AXE",            type:"item",  textures:{0:"iron_axe"} },
  { id:259, material:"FLINT_AND_STEEL",     type:"item",  textures:{0:"flint_and_steel"} },
  { id:260, material:"APPLE",               type:"item",  textures:{0:"apple"} },
  { id:261, material:"BOW",                type:"item",  textures:{0:"bow_standby"} },
  { id:262, material:"ARROW",               type:"item",  textures:{0:"arrow"} },
  { id:263, material:"COAL",               type:"item",  textures:{0:"coal",1:"charcoal"} },
  { id:264, material:"DIAMOND",            type:"item",  textures:{0:"diamond"} },
  { id:265, material:"IRON_INGOT",          type:"item",  textures:{0:"iron_ingot"} },
  { id:266, material:"GOLD_INGOT",          type:"item",  textures:{0:"gold_ingot"} },
  { id:267, material:"IRON_SWORD",          type:"item",  textures:{0:"iron_sword"} },
  { id:268, material:"WOOD_SWORD",         type:"item",  textures:{0:"wood_sword"} },
  { id:269, material:"WOOD_SPADE",         type:"item",  textures:{0:"wood_shovel"} },
  { id:270, material:"WOOD_PICKAXE",       type:"item",  textures:{0:"wood_pickaxe"} },
  { id:271, material:"WOOD_AXE",           type:"item",  textures:{0:"wood_axe"} },
  { id:272, material:"STONE_SWORD",         type:"item",  textures:{0:"stone_sword"} },
  { id:273, material:"STONE_SPADE",         type:"item",  textures:{0:"stone_shovel"} },
  { id:274, material:"STONE_PICKAXE",       type:"item",  textures:{0:"stone_pickaxe"} },
  { id:275, material:"STONE_AXE",         type:"item",  textures:{0:"stone_axe"} },
  { id:276, material:"DIAMOND_SWORD",       type:"item",  textures:{0:"diamond_sword"} },
  { id:277, material:"DIAMOND_SPADE",       type:"item",  textures:{0:"diamond_shovel"} },
  { id:278, material:"DIAMOND_PICKAXE",     type:"item",  textures:{0:"diamond_pickaxe"} },
  { id:279, material:"DIAMOND_AXE",           type:"item",  textures:{0:"diamond_axe"} },
  { id:280, material:"STICK",              type:"item",  textures:{0:"stick"} },
  { id:281, material:"BOWL",                type:"item",  textures:{0:"bowl"} },
  { id:282, material:"MUSHROOM_SOUP",       type:"item",  textures:{0:"mushroom_stew"} },
  { id:282, material:"RED_MUSHROOM",       type:"block",  textures:{0:"mushroom_red"} },
  { id:282, material:"BROWN_MUSHROOM",       type:"block",  textures:{0:"mushroom_brown"} },
  { id:283, material:"GOLD_SWORD",         type:"item",  textures:{0:"gold_sword"} },
  { id:284, material:"GOLD_SPADE",          type:"item",  textures:{0:"gold_shovel"} },
  { id:285, material:"GOLD_PICKAXE",        type:"item",  textures:{0:"gold_pickaxe"} },
  { id:286, material:"GOLD_AXE",            type:"item",  textures:{0:"gold_axe"} },
  { id:287, material:"STRING",            type:"item",  textures:{0:"string"} },
  { id:288, material:"FEATHER",          type:"item",  textures:{0:"feather"} },
  { id:289, material:"SULPHUR",           type:"item",  textures:{0:"gunpowder"} },
  { id:290, material:"WOOD_HOE",          type:"item",  textures:{0:"wood_hoe"} },
  { id:291, material:"STONE_HOE",         type:"item",  textures:{0:"stone_hoe"} },
  { id:292, material:"IRON_HOE",          type:"item",  textures:{0:"iron_hoe"} },
  { id:293, material:"DIAMOND_HOE",        type:"item",  textures:{0:"diamond_hoe"} },
  { id:294, material:"GOLD_HOE",           type:"item",  textures:{0:"gold_hoe"} },
  { id:295, material:"SEEDS",              type:"item",  textures:{0:"seeds_wheat"} },
  { id:296, material:"WHEAT",              type:"item",  textures:{0:"wheat"} },
  { id:297, material:"BREAD",             type:"item",  textures:{0:"bread"} },
  { id:298, material:"LEATHER_HELMET",     type:"item",  textures:{0:"leather_helmet"} },
  { id:299, material:"LEATHER_CHESTPLATE",   type:"item",  textures:{0:"leather_chestplate"} },
  { id:300, material:"LEATHER_LEGGINGS",   type:"item",  textures:{0:"leather_leggings"} },
  { id:301, material:"LEATHER_BOOTS",     type:"item",  textures:{0:"leather_boots"} },
  { id:302, material:"CHAINMAIL_HELMET",    type:"item",  textures:{0:"chainmail_helmet"} },
  { id:303, material:"CHAINMAIL_CHESTPLATE",type:"item",  textures:{0:"chainmail_chestplate"} },
  { id:304, material:"CHAINMAIL_LEGGINGS",type:"item",  textures:{0:"chainmail_leggings"} },
  { id:305, material:"CHAINMAIL_BOOTS",    type:"item",  textures:{0:"chainmail_boots"} },
  { id:306, material:"IRON_HELMET",          type:"item",  textures:{0:"iron_helmet"} },
  { id:307, material:"IRON_CHESTPLATE",    type:"item",  textures:{0:"iron_chestplate"} },
  { id:308, material:"IRON_LEGGINGS",     type:"item",  textures:{0:"iron_leggings"} },
  { id:309, material:"IRON_BOOTS",         type:"item",  textures:{0:"iron_boots"} },
  { id:310, material:"DIAMOND_HELMET",      type:"item",  textures:{0:"diamond_helmet"} },
  { id:311, material:"DIAMOND_CHESTPLATE",  type:"item",  textures:{0:"diamond_chestplate"} },
  { id:312, material:"DIAMOND_LEGGINGS",  type:"item",  textures:{0:"diamond_leggings"} },
  { id:313, material:"DIAMOND_BOOTS",       type:"item",  textures:{0:"diamond_boots"} },
  { id:314, material:"GOLD_HELMET",        type:"item",  textures:{0:"gold_helmet"} },
  { id:315, material:"GOLD_CHESTPLATE",    type:"item",  textures:{0:"gold_chestplate"} },
  { id:316, material:"GOLD_LEGGINGS",      type:"item",  textures:{0:"gold_leggings"} },
  { id:317, material:"GOLD_BOOTS",        type:"item",  textures:{0:"gold_boots"} },
  { id:318, material:"FLINT",             type:"item",  textures:{0:"flint"} },
  { id:319, material:"PORK",              type:"item",  textures:{0:"porkchop_raw"} },
  { id:320, material:"GRILLED_PORK",     type:"item",  textures:{0:"porkchop_cooked"} },
  { id:322, material:"GOLDEN_APPLE",     type:"item",  textures:{0:"apple_golden"} },
  { id:325, material:"BUCKET",            type:"item",  textures:{0:"bucket_empty"} },
  { id:326, material:"WATER_BUCKET",      type:"item",  textures:{0:"bucket_water"} },
  { id:326, material:"WATER_LILY",      type:"block",  textures:{0:"waterlily"} },
  { id:327, material:"LAVA_BUCKET",      type:"item",  textures:{0:"bucket_lava"} },
  { id:329, material:"SADDLE",            type:"item",  textures:{0:"saddle"} },
  { id:331, material:"REDSTONE",          type:"item",  textures:{0:"redstone_dust"} },
  { id:332, material:"SNOW_BALL",        type:"item",  textures:{0:"snowball"} },
  { id:334, material:"LEATHER",           type:"item",  textures:{0:"leather"} },
  { id:335, material:"MILK_BUCKET",      type:"item",  textures:{0:"bucket_milk"} },
  { id:336, material:"CLAY_BRICK",        type:"item",  textures:{0:"brick"} },
  { id:337, material:"CLAY_BALL",         type:"item",  textures:{0:"clay_ball"} },
  { id:338, material:"SUGAR_CANE",        type:"item",  textures:{0:"reeds"} },
  { id:339, material:"PAPER",              type:"item",  textures:{0:"paper"} },
  { id:340, material:"BOOK",             type:"item",  textures:{0:"book_normal"} },
  { id:341, material:"SLIME_BALL",        type:"item",  textures:{0:"slimeball"} },
  { id:344, material:"EGG",               type:"item",  textures:{0:"egg"} },
  { id:345, material:"COMPASS",          type:"item",  textures:{0:"compass"} },
  { id:346, material:"FISHING_ROD",        type:"item",  textures:{0:"fishing_rod_uncast"} },
  { id:347, material:"WATCH",             type:"item",  textures:{0:"clock"} },
  { id:348, material:"GLOWSTONE_DUST",   type:"item",  textures:{0:"glowstone_dust"} },
  { id:349, material:"RAW_FISH",        type:"item",  textures:{0:"fish_cod_raw",1:"fish_salmon_raw",2:"fish_clownfish_raw",3:"fish_pufferfish_raw"} },
  { id:350, material:"COOKED_FISH",      type:"item",  textures:{0:"fish_cod_cooked",1:"fish_salmon_cooked"} },
  { id:351, material:"INK_SACK",          type:"item",  textures:{0:"dye_powder_black",1:"dye_powder_red",2:"dye_powder_green",3:"dye_powder_brown",4:"dye_powder_blue",5:"dye_powder_purple",6:"dye_powder_cyan",7:"dye_powder_silver",8:"dye_powder_gray",9:"dye_powder_pink",10:"dye_powder_lime",11:"dye_powder_yellow",12:"dye_powder_light_blue",13:"dye_powder_magenta",14:"dye_powder_orange",15:"dye_powder_white"} },
  { id:352, material:"BONE",               type:"item",  textures:{0:"bone"} },
  { id:353, material:"SUGAR",            type:"item",  textures:{0:"sugar"} },
  { id:354, material:"CAKE",             type:"item",  textures:{0:"cake"} },
  { id:357, material:"COOKIE",           type:"item",  textures:{0:"cookie"} },
  { id:359, material:"SHEARS",            type:"item",  textures:{0:"shears"} },
  { id:360, material:"MELON",            type:"item",  textures:{0:"melon"} },
  { id:363, material:"RAW_BEEF",          type:"item",  textures:{0:"beef_raw"} },
  { id:364, material:"COOKED_BEEF",      type:"item",  textures:{0:"beef_cooked"} },
  { id:365, material:"RAW_CHICKEN",         type:"item",  textures:{0:"chicken_raw"} },
  { id:366, material:"COOKED_CHICKEN",     type:"item",  textures:{0:"chicken_cooked"} },
  { id:367, material:"ROTTEN_FLESH",      type:"item",  textures:{0:"rotten_flesh"} },
  { id:368, material:"ENDER_PEARL",        type:"item",  textures:{0:"ender_pearl"} },
  { id:369, material:"BLAZE_ROD",         type:"item",  textures:{0:"blaze_rod"} },
  { id:370, material:"GHAST_TEAR",         type:"item",  textures:{0:"ghast_tear"} },
  { id:371, material:"GOLD_NUGGET",       type:"item",  textures:{0:"gold_nugget"} },
  { id:372, material:"NETHER_STALK",       type:"item",  textures:{0:"nether_wart"} },
  { id:374, material:"GLASS_BOTTLE",      type:"item",  textures:{0:"potion_bottle_empty"} },
  { id:375, material:"SPIDER_EYE",        type:"item",  textures:{0:"spider_eye"} },
  { id:377, material:"BLAZE_POWDER",       type:"item",  textures:{0:"blaze_powder"} },
  { id:378, material:"MAGMA_CREAM",       type:"item",  textures:{0:"magma_cream"} },
  { id:381, material:"EYE_OF_ENDER",      type:"item",  textures:{0:"ender_eye"} },
  { id:381, material:"ENDER_STONE",      type:"block",  textures:{0:"end_stone"} },
  { id:382, material:"SPECKLED_MELON",   type:"item",  textures:{0:"melon_speckled"} },
  { id:384, material:"EXP_BOTTLE",       type:"item",  textures:{0:"experience_bottle"} },
  { id:385, material:"FIREBALL",          type:"item",  textures:{0:"fire_charge"} },
  { id:386, material:"BOOK_AND_QUILL",    type:"item",  textures:{0:"book_writable"} },
  { id:387, material:"WRITTEN_BOOK",      type:"item",  textures:{0:"book_written"} },
  { id:388, material:"EMERALD",          type:"item",  textures:{0:"emerald"} },
  { id:391, material:"CARROT_ITEM",           type:"item",  textures:{0:"carrot"} },
  { id:392, material:"POTATO_ITEM",           type:"item",  textures:{0:"potato"} },
  { id:393, material:"BAKED_POTATO",      type:"item",  textures:{0:"potato_baked"} },
  { id:394, material:"POISONOUS_POTATO",  type:"item",  textures:{0:"potato_poisonous"} },
  { id:396, material:"GOLDEN_CARROT",      type:"item",  textures:{0:"carrot_golden"} },
  { id:397, material:"SKULL",               type:"item",  textures:{0:"skull_skeleton",1:"skull_wither",2:"skull_zombie",3:"skull_char",4:"skull_creeper"} },
  { id:399, material:"NETHER_STAR",      type:"item",  textures:{0:"nether_star"} },
  { id:400, material:"PUMPKIN_PIE",       type:"item",  textures:{0:"pumpkin_pie"} },
  { id:403, material:"ENCHANTED_BOOK",     type:"item",  textures:{0:"book_enchanted"} },
  { id:406, material:"QUARTZ",            type:"item",  textures:{0:"quartz"} },
  { id:409, material:"PRISMARINE_SHARD",  type:"item",  textures:{0:"prismarine_shard"} },
  { id:410, material:"PRISMARINE_CRYSTALS", type:"item",  textures:{0:"prismarine_crystals"} },
  { id:411, material:"RABBIT",            type:"item",  textures:{0:"rabbit_raw"} },
  { id:412, material:"COOKED_RABBIT",     type:"item",  textures:{0:"rabbit_cooked"} },
  { id:414, material:"RABBIT_FOOT",       type:"item",  textures:{0:"rabbit_foot"} },
  { id:415, material:"RABBIT_HIDE",       type:"item",  textures:{0:"rabbit_hide"} },
  { id:417, material:"IRON_BARDING",       type:"item",  textures:{0:"horse_armor_iron"} },
  { id:418, material:"GOLD_BARDING",      type:"item",  textures:{0:"horse_armor_gold"} },
  { id:419, material:"DIAMOND_BARDING",     type:"item",  textures:{0:"horse_armor_diamond"} },
  { id:420, material:"LEASH",              type:"item",  textures:{0:"lead"} },
  { id:421, material:"NAME_TAG",          type:"item",  textures:{0:"name_tag"} },
  { id:423, material:"MUTTON",            type:"item",  textures:{0:"mutton_raw"} },
  { id:424, material:"COOKED_MUTTON",      type:"item",  textures:{0:"mutton_cooked"} },
];

export function getTexture(material, metadata) {
  const item = MC18_ITEMS.find(function(i) { return i.material === material; });

  if (!item) return { error: 'Material "' + material + '" nao encontrado.' };

  const textureName = item.textures[metadata];
        
  if (!textureName) return { error: 'Metadata ' + metadata + ' nao existe para ' + material + '.' };

  const url = 'https://raw.githubusercontent.com/PrismarineJS/minecraft-assets/master/data/1.8.8/' + item.type + 's/' + textureName + '.png';
        
  return {
    success: true,
    type: item.type,
    material: material,
    metadata: metadata,
    texture: textureName,
    url: url
  };
}