const MC18_ITEMS = [
  // ==================== BLOCKS ====================
  { id:1,   material:"STONE",                    type:"block", textures:{0:"stone",1:"stone_granite",2:"stone_granite_smooth",3:"stone_diorite",4:"stone_diorite_smooth",5:"stone_andesite",6:"stone_andesite_smooth"} },
  { id:2,   material:"GRASS",                    type:"block", textures:{0:"grass_side"} },
  { id:3,   material:"DIRT",                     type:"block", textures:{0:"dirt",1:"coarse_dirt",2:"dirt_podzol_side"} },
  { id:4,   material:"COBBLESTONE",              type:"block", textures:{0:"cobblestone"} },
  { id:5,   material:"WOOD",                     type:"block", textures:{0:"planks_oak",1:"planks_spruce",2:"planks_birch",3:"planks_jungle",4:"planks_acacia",5:"planks_big_oak"} },
  { id:6,   material:"SAPLING",                  type:"block", textures:{0:"sapling_oak",1:"sapling_spruce",2:"sapling_birch",3:"sapling_jungle",4:"sapling_acacia",5:"sapling_roofed_oak"} },
  { id:7,   material:"BEDROCK",                  type:"block", textures:{0:"bedrock"} },
  { id:12,  material:"SAND",                     type:"block", textures:{0:"sand",1:"red_sand"} },
  { id:13,  material:"GRAVEL",                   type:"block", textures:{0:"gravel"} },
  { id:14,  material:"GOLD_ORE",                 type:"block", textures:{0:"gold_ore"} },
  { id:15,  material:"IRON_ORE",                 type:"block", textures:{0:"iron_ore"} },
  { id:16,  material:"COAL_ORE",                 type:"block", textures:{0:"coal_ore"} },
  { id:17,  material:"LOG",                      type:"block", textures:{0:"log_oak",1:"log_spruce",2:"log_birch",3:"log_jungle"} },
  { id:18,  material:"LEAVES",                   type:"block", textures:{0:"leaves_oak",1:"leaves_spruce",2:"leaves_birch",3:"leaves_jungle"} },
  { id:19,  material:"SPONGE",                   type:"block", textures:{0:"sponge"} },
  { id:20,  material:"GLASS",                    type:"block", textures:{0:"glass"} },
  { id:21,  material:"LAPIS_ORE",                type:"block", textures:{0:"lapis_ore"} },
  { id:22,  material:"LAPIS_BLOCK",              type:"block", textures:{0:"lapis_block"} },
  { id:23,  material:"DISPENSER",                type:"block", textures:{0:"dispenser_front_horizontal"} },
  { id:24,  material:"SANDSTONE",                type:"block", textures:{0:"sandstone_normal",1:"sandstone_chiseled",2:"sandstone_smooth"} },
  { id:25,  material:"NOTE_BLOCK",               type:"block", textures:{0:"noteblock"} },
  { id:27,  material:"POWERED_RAIL",             type:"block", textures:{0:"rail_golden"} },
  { id:28,  material:"DETECTOR_RAIL",            type:"block", textures:{0:"rail_detector"} },
  { id:29,  material:"PISTON_STICKY_BASE",       type:"block", textures:{0:"piston_top_sticky"} },
  { id:30,  material:"WEB",                      type:"block", textures:{0:"web"} },
  { id:31,  material:"LONG_GRASS",               type:"block", textures:{0:"tallgrass",1:"fern"} },
  { id:32,  material:"DEAD_BUSH",                type:"block", textures:{0:"deadbush"} },
  { id:33,  material:"PISTON_BASE",              type:"block", textures:{0:"piston_top_normal"} },
  { id:35,  material:"WOOL",                     type:"block", textures:{0:"wool_colored_white",1:"wool_colored_orange",2:"wool_colored_magenta",3:"wool_colored_light_blue",4:"wool_colored_yellow",5:"wool_colored_lime",6:"wool_colored_pink",7:"wool_colored_gray",8:"wool_colored_silver",9:"wool_colored_cyan",10:"wool_colored_purple",11:"wool_colored_blue",12:"wool_colored_brown",13:"wool_colored_green",14:"wool_colored_red",15:"wool_colored_black"} },
  { id:37,  material:"YELLOW_FLOWER",            type:"block", textures:{0:"flower_dandelion"} },
  { id:38,  material:"RED_ROSE",                 type:"block", textures:{0:"flower_rose",1:"flower_blue_orchid",2:"flower_allium",3:"flower_houstonia",4:"flower_tulip_red",5:"flower_tulip_orange",6:"flower_tulip_white",7:"flower_tulip_pink",8:"flower_oxeye_daisy"} },
  { id:39,  material:"BROWN_MUSHROOM",           type:"block", textures:{0:"mushroom_brown"} },
  { id:40,  material:"RED_MUSHROOM",             type:"block", textures:{0:"mushroom_red"} },
  { id:41,  material:"GOLD_BLOCK",               type:"block", textures:{0:"gold_block"} },
  { id:42,  material:"IRON_BLOCK",               type:"block", textures:{0:"iron_block"} },
  { id:43,  material:"DOUBLE_STEP",              type:"block", textures:{0:"stone_slab_top",1:"sandstone_top",2:"planks_oak",3:"cobblestone",4:"brick",5:"stonebrick",6:"nether_brick",7:"quartz_block_top"} },
  { id:44,  material:"STEP",                     type:"block", textures:{0:"stone_slab_side",1:"sandstone_normal",2:"planks_oak",3:"cobblestone",4:"brick",5:"stonebrick",6:"nether_brick",7:"quartz_block_side"} },
  { id:45,  material:"BRICK",                    type:"block", textures:{0:"brick"} },
  { id:46,  material:"TNT",                      type:"block", textures:{0:"tnt_side"} },
  { id:47,  material:"BOOKSHELF",                type:"block", textures:{0:"bookshelf"} },
  { id:48,  material:"MOSSY_COBBLESTONE",        type:"block", textures:{0:"cobblestone_mossy"} },
  { id:49,  material:"OBSIDIAN",                 type:"block", textures:{0:"obsidian"} },
  { id:50,  material:"TORCH",                    type:"block", textures:{0:"torch_on"} },
  { id:51,  material:"FIRE",                     type:"block", textures:{0:"fire_layer_0"} },
  { id:52,  material:"MOB_SPAWNER",              type:"block", textures:{0:"mob_spawner"} },
  { id:53,  material:"WOOD_STAIRS",              type:"block", textures:{0:"planks_oak"} },
  { id:54,  material:"CHEST",                    type:"block", textures:{0:"chest_front"} },
  { id:55,  material:"REDSTONE_WIRE",            type:"block", textures:{0:"redstone_dust_cross"} },
  { id:56,  material:"DIAMOND_ORE",              type:"block", textures:{0:"diamond_ore"} },
  { id:57,  material:"DIAMOND_BLOCK",            type:"block", textures:{0:"diamond_block"} },
  { id:58,  material:"WORKBENCH",                type:"block", textures:{0:"crafting_table_front"} },
  { id:59,  material:"CROPS",                    type:"block", textures:{0:"wheat_stage_7"} },
  { id:60,  material:"SOIL",                     type:"block", textures:{0:"farmland_wet"} },
  { id:61,  material:"FURNACE",                  type:"block", textures:{0:"furnace_front_off"} },
  { id:62,  material:"BURNING_FURNACE",          type:"block", textures:{0:"furnace_front_on"} },
  { id:63,  material:"SIGN_POST",                type:"block", textures:{0:"planks_oak"} },
  { id:64,  material:"WOODEN_DOOR",              type:"block", textures:{0:"door_wood_lower",1:"door_wood_upper"} },
  { id:65,  material:"LADDER",                   type:"block", textures:{0:"ladder"} },
  { id:66,  material:"RAILS",                    type:"block", textures:{0:"rail_normal"} },
  { id:67,  material:"COBBLESTONE_STAIRS",       type:"block", textures:{0:"cobblestone"} },
  { id:68,  material:"WALL_SIGN",                type:"block", textures:{0:"planks_oak"} },
  { id:69,  material:"LEVER",                    type:"block", textures:{0:"lever"} },
  { id:70,  material:"STONE_PLATE",              type:"block", textures:{0:"stone"} },
  { id:71,  material:"IRON_DOOR_BLOCK",          type:"block", textures:{0:"door_iron_lower",1:"door_iron_upper"} },
  { id:72,  material:"WOOD_PLATE",               type:"block", textures:{0:"planks_oak"} },
  { id:73,  material:"REDSTONE_ORE",             type:"block", textures:{0:"redstone_ore"} },
  { id:74,  material:"GLOWING_REDSTONE_ORE",     type:"block", textures:{0:"redstone_ore"} },
  { id:75,  material:"REDSTONE_TORCH_OFF",       type:"block", textures:{0:"redstone_torch_off"} },
  { id:76,  material:"REDSTONE_TORCH_ON",        type:"block", textures:{0:"redstone_torch_on"} },
  { id:77,  material:"STONE_BUTTON",             type:"block", textures:{0:"stone"} },
  { id:78,  material:"SNOW",                     type:"block", textures:{0:"snow"} },
  { id:79,  material:"ICE",                      type:"block", textures:{0:"ice"} },
  { id:80,  material:"SNOW_BLOCK",               type:"block", textures:{0:"snow"} },
  { id:81,  material:"CACTUS",                   type:"block", textures:{0:"cactus_side"} },
  { id:82,  material:"CLAY",                     type:"block", textures:{0:"clay"} },
  { id:83,  material:"SUGAR_CANE_BLOCK",         type:"block", textures:{0:"reeds"} },
  { id:84,  material:"JUKEBOX",                  type:"block", textures:{0:"jukebox_side"} },
  { id:85,  material:"FENCE",                    type:"block", textures:{0:"planks_oak"} },
  { id:86,  material:"PUMPKIN",                  type:"block", textures:{0:"pumpkin_face_off"} },
  { id:87,  material:"NETHERRACK",               type:"block", textures:{0:"netherrack"} },
  { id:88,  material:"SOUL_SAND",                type:"block", textures:{0:"soul_sand"} },
  { id:89,  material:"GLOWSTONE",                type:"block", textures:{0:"glowstone"} },
  { id:90,  material:"PORTAL",                   type:"block", textures:{0:"portal"} },
  { id:91,  material:"JACK_O_LANTERN",           type:"block", textures:{0:"pumpkin_face_on"} },
  { id:92,  material:"CAKE_BLOCK",               type:"block", textures:{0:"cake_top"} },
  { id:93,  material:"DIODE_BLOCK_OFF",          type:"block", textures:{0:"repeater_off"} },
  { id:94,  material:"DIODE_BLOCK_ON",           type:"block", textures:{0:"repeater_on"} },
  { id:95,  material:"STAINED_GLASS",            type:"block", textures:{0:"glass_white",1:"glass_orange",2:"glass_magenta",3:"glass_light_blue",4:"glass_yellow",5:"glass_lime",6:"glass_pink",7:"glass_gray",8:"glass_silver",9:"glass_cyan",10:"glass_purple",11:"glass_blue",12:"glass_brown",13:"glass_green",14:"glass_red",15:"glass_black"} },
  { id:96,  material:"TRAP_DOOR",                type:"block", textures:{0:"trapdoor"} },
  { id:97,  material:"MONSTER_EGGS",             type:"block", textures:{0:"stone",1:"cobblestone",2:"stonebrick"} },
  { id:98,  material:"SMOOTH_BRICK",             type:"block", textures:{0:"stonebrick",1:"stonebrick_mossy",2:"stonebrick_cracked",3:"stonebrick_carved"} },
  { id:99,  material:"HUGE_MUSHROOM_1",          type:"block", textures:{0:"mushroom_block_skin_brown"} },
  { id:100, material:"HUGE_MUSHROOM_2",          type:"block", textures:{0:"mushroom_block_skin_red"} },
  { id:101, material:"IRON_FENCE",               type:"block", textures:{0:"iron_bars"} },
  { id:102, material:"THIN_GLASS",               type:"block", textures:{0:"glass_pane_top"} },
  { id:103, material:"MELON_BLOCK",              type:"block", textures:{0:"melon_side"} },
  { id:104, material:"PUMPKIN_STEM",             type:"block", textures:{0:"pumpkin_stem_disconnected"} },
  { id:105, material:"MELON_STEM",               type:"block", textures:{0:"melon_stem_disconnected"} },
  { id:106, material:"VINE",                     type:"block", textures:{0:"vine"} },
  { id:107, material:"FENCE_GATE",               type:"block", textures:{0:"planks_oak"} },
  { id:108, material:"BRICK_STAIRS",             type:"block", textures:{0:"brick"} },
  { id:109, material:"SMOOTH_STAIRS",            type:"block", textures:{0:"stonebrick"} },
  { id:110, material:"MYCEL",                    type:"block", textures:{0:"mycelium_side"} },
  { id:111, material:"WATER_LILY",               type:"block", textures:{0:"waterlily"} },
  { id:112, material:"NETHER_BRICK",             type:"block", textures:{0:"nether_brick"} },
  { id:113, material:"NETHER_FENCE",             type:"block", textures:{0:"nether_brick"} },
  { id:114, material:"NETHER_BRICK_STAIRS",      type:"block", textures:{0:"nether_brick"} },
  { id:115, material:"NETHER_WARTS",             type:"block", textures:{0:"nether_wart_stage_2"} },
  { id:116, material:"ENCHANTMENT_TABLE",        type:"block", textures:{0:"enchanting_table_top"} },
  { id:117, material:"BREWING_STAND",            type:"block", textures:{0:"brewing_stand"} },
  { id:118, material:"CAULDRON",                 type:"block", textures:{0:"cauldron_side"} },
  { id:119, material:"ENDER_PORTAL",             type:"block", textures:{0:"endframe_top"} },
  { id:120, material:"ENDER_PORTAL_FRAME",       type:"block", textures:{0:"endframe_top"} },
  { id:121, material:"END_STONE",                type:"block", textures:{0:"end_stone"} },
  { id:121, material:"ENDER_STONE",              type:"block", textures:{0:"end_stone"} },
  { id:122, material:"DRAGON_EGG",               type:"block", textures:{0:"dragon_egg"} },
  { id:123, material:"REDSTONE_LAMP_OFF",        type:"block", textures:{0:"redstone_lamp_off"} },
  { id:124, material:"REDSTONE_LAMP_ON",         type:"block", textures:{0:"redstone_lamp_on"} },
  { id:125, material:"WOOD_DOUBLE_STEP",         type:"block", textures:{0:"planks_oak",1:"planks_spruce",2:"planks_birch",3:"planks_jungle",4:"planks_acacia",5:"planks_big_oak"} },
  { id:126, material:"WOOD_STEP",                type:"block", textures:{0:"planks_oak",1:"planks_spruce",2:"planks_birch",3:"planks_jungle",4:"planks_acacia",5:"planks_big_oak"} },
  { id:127, material:"COCOA",                    type:"block", textures:{0:"cocoa_stage_2"} },
  { id:128, material:"SANDSTONE_STAIRS",         type:"block", textures:{0:"sandstone_normal"} },
  { id:129, material:"EMERALD_ORE",              type:"block", textures:{0:"emerald_ore"} },
  { id:130, material:"ENDER_CHEST",              type:"block", textures:{0:"ender_chest_front"} },
  { id:131, material:"TRIPWIRE_HOOK",            type:"block", textures:{0:"trip_wire_source"} },
  { id:132, material:"TRIPWIRE",                 type:"block", textures:{0:"trip_wire"} },
  { id:133, material:"EMERALD_BLOCK",            type:"block", textures:{0:"emerald_block"} },
  { id:134, material:"SPRUCE_WOOD_STAIRS",       type:"block", textures:{0:"planks_spruce"} },
  { id:135, material:"BIRCH_WOOD_STAIRS",        type:"block", textures:{0:"planks_birch"} },
  { id:136, material:"JUNGLE_WOOD_STAIRS",       type:"block", textures:{0:"planks_jungle"} },
  { id:137, material:"COMMAND",                  type:"block", textures:{0:"command_block"} },
  { id:138, material:"BEACON",                   type:"block", textures:{0:"beacon"} },
  { id:139, material:"COBBLE_WALL",              type:"block", textures:{0:"cobblestone",1:"cobblestone_mossy"} },
  { id:140, material:"FLOWER_POT",               type:"block", textures:{0:"flower_pot"} },
  { id:141, material:"CARROT",                   type:"block", textures:{0:"carrots_stage_3"} },
  { id:142, material:"POTATO",                   type:"block", textures:{0:"potatoes_stage_3"} },
  { id:143, material:"WOOD_BUTTON",              type:"block", textures:{0:"planks_oak"} },
  { id:144, material:"SKULL",                    type:"block", textures:{0:"skull_skeleton"} },
  { id:145, material:"ANVIL",                    type:"block", textures:{0:"anvil_top_damaged_0",1:"anvil_top_damaged_1",2:"anvil_top_damaged_2"} },
  { id:146, material:"TRAPPED_CHEST",            type:"block", textures:{0:"chest_front"} },
  { id:147, material:"GOLD_PLATE",               type:"block", textures:{0:"gold_block"} },
  { id:148, material:"IRON_PLATE",               type:"block", textures:{0:"iron_block"} },
  { id:149, material:"REDSTONE_COMPARATOR_OFF",  type:"block", textures:{0:"comparator_off"} },
  { id:150, material:"REDSTONE_COMPARATOR_ON",   type:"block", textures:{0:"comparator_on"} },
  { id:151, material:"DAYLIGHT_DETECTOR",        type:"block", textures:{0:"daylight_detector_top"} },
  { id:152, material:"REDSTONE_BLOCK",           type:"block", textures:{0:"redstone_block"} },
  { id:153, material:"QUARTZ_ORE",               type:"block", textures:{0:"quartz_ore"} },
  { id:154, material:"HOPPER",                   type:"block", textures:{0:"hopper_outside"} },
  { id:155, material:"QUARTZ_BLOCK",             type:"block", textures:{0:"quartz_block_side",1:"quartz_block_chiseled",2:"quartz_block_lines"} },
  { id:156, material:"QUARTZ_STAIRS",            type:"block", textures:{0:"quartz_block_side"} },
  { id:157, material:"ACTIVATOR_RAIL",           type:"block", textures:{0:"rail_activator"} },
  { id:158, material:"DROPPER",                  type:"block", textures:{0:"dropper_front_horizontal"} },
  { id:159, material:"STAINED_CLAY",             type:"block", textures:{0:"hardened_clay_stained_white",1:"hardened_clay_stained_orange",2:"hardened_clay_stained_magenta",3:"hardened_clay_stained_light_blue",4:"hardened_clay_stained_yellow",5:"hardened_clay_stained_lime",6:"hardened_clay_stained_pink",7:"hardened_clay_stained_gray",8:"hardened_clay_stained_silver",9:"hardened_clay_stained_cyan",10:"hardened_clay_stained_purple",11:"hardened_clay_stained_blue",12:"hardened_clay_stained_brown",13:"hardened_clay_stained_green",14:"hardened_clay_stained_red",15:"hardened_clay_stained_black"} },
  { id:160, material:"STAINED_GLASS_PANE",       type:"block", textures:{0:"glass_white",1:"glass_orange",2:"glass_magenta",3:"glass_light_blue",4:"glass_yellow",5:"glass_lime",6:"glass_pink",7:"glass_gray",8:"glass_silver",9:"glass_cyan",10:"glass_purple",11:"glass_blue",12:"glass_brown",13:"glass_green",14:"glass_red",15:"glass_black"} },
  { id:161, material:"LEAVES_2",                 type:"block", textures:{0:"leaves_acacia",1:"leaves_big_oak"} },
  { id:162, material:"LOG_2",                    type:"block", textures:{0:"log_acacia",1:"log_big_oak"} },
  { id:163, material:"ACACIA_STAIRS",            type:"block", textures:{0:"planks_acacia"} },
  { id:164, material:"DARK_OAK_STAIRS",          type:"block", textures:{0:"planks_big_oak"} },
  { id:165, material:"SLIME_BLOCK",              type:"block", textures:{0:"slime"} },
  { id:166, material:"BARRIER",                  type:"block", textures:{0:"barrier"} },
  { id:167, material:"IRON_TRAPDOOR",            type:"block", textures:{0:"iron_trapdoor"} },
  { id:168, material:"PRISMARINE",               type:"block", textures:{0:"prismarine_rough",1:"prismarine_bricks",2:"prismarine_dark"} },
  { id:169, material:"SEA_LANTERN",              type:"block", textures:{0:"sea_lantern"} },
  { id:170, material:"HAY_BLOCK",                type:"block", textures:{0:"hay_block_side"} },
  { id:171, material:"CARPET",                   type:"block", textures:{0:"wool_colored_white",1:"wool_colored_orange",2:"wool_colored_magenta",3:"wool_colored_light_blue",4:"wool_colored_yellow",5:"wool_colored_lime",6:"wool_colored_pink",7:"wool_colored_gray",8:"wool_colored_silver",9:"wool_colored_cyan",10:"wool_colored_purple",11:"wool_colored_blue",12:"wool_colored_brown",13:"wool_colored_green",14:"wool_colored_red",15:"wool_colored_black"} },
  { id:172, material:"HARD_CLAY",                type:"block", textures:{0:"hardened_clay"} },
  { id:173, material:"COAL_BLOCK",               type:"block", textures:{0:"coal_block"} },
  { id:174, material:"PACKED_ICE",               type:"block", textures:{0:"ice_packed"} },
  { id:175, material:"DOUBLE_PLANT",             type:"block", textures:{0:"double_plant_sunflower_front",1:"double_plant_syringa_top",2:"double_plant_grass_top",3:"double_plant_fern_top",4:"double_plant_rose_top",5:"double_plant_paeonia_top"} },
  { id:176, material:"STANDING_BANNER",          type:"block", textures:{0:"banner_base"} },
  { id:177, material:"WALL_BANNER",              type:"block", textures:{0:"banner_base"} },
  { id:178, material:"DAYLIGHT_DETECTOR_INVERTED",type:"block",textures:{0:"daylight_detector_inverted_top"} },
  { id:179, material:"RED_SANDSTONE",            type:"block", textures:{0:"red_sandstone_normal",1:"red_sandstone_chiseled",2:"red_sandstone_smooth"} },
  { id:180, material:"RED_SANDSTONE_STAIRS",     type:"block", textures:{0:"red_sandstone_normal"} },
  { id:181, material:"DOUBLE_STONE_SLAB2",       type:"block", textures:{0:"red_sandstone_top"} },
  { id:182, material:"STONE_SLAB2",              type:"block", textures:{0:"red_sandstone_normal"} },
  { id:183, material:"SPRUCE_FENCE_GATE",        type:"block", textures:{0:"planks_spruce"} },
  { id:184, material:"BIRCH_FENCE_GATE",         type:"block", textures:{0:"planks_birch"} },
  { id:185, material:"JUNGLE_FENCE_GATE",        type:"block", textures:{0:"planks_jungle"} },
  { id:186, material:"DARK_OAK_FENCE_GATE",      type:"block", textures:{0:"planks_big_oak"} },
  { id:187, material:"ACACIA_FENCE_GATE",        type:"block", textures:{0:"planks_acacia"} },
  { id:188, material:"SPRUCE_FENCE",             type:"block", textures:{0:"planks_spruce"} },
  { id:189, material:"BIRCH_FENCE",              type:"block", textures:{0:"planks_birch"} },
  { id:190, material:"JUNGLE_FENCE",             type:"block", textures:{0:"planks_jungle"} },
  { id:191, material:"DARK_OAK_FENCE",           type:"block", textures:{0:"planks_big_oak"} },
  { id:192, material:"ACACIA_FENCE",             type:"block", textures:{0:"planks_acacia"} },
  { id:193, material:"SPRUCE_DOOR_BLOCK",        type:"block", textures:{0:"door_spruce_lower",1:"door_spruce_upper"} },
  { id:194, material:"BIRCH_DOOR_BLOCK",         type:"block", textures:{0:"door_birch_lower",1:"door_birch_upper"} },
  { id:195, material:"JUNGLE_DOOR_BLOCK",        type:"block", textures:{0:"door_jungle_lower",1:"door_jungle_upper"} },
  { id:196, material:"ACACIA_DOOR_BLOCK",        type:"block", textures:{0:"door_acacia_lower",1:"door_acacia_upper"} },
  { id:197, material:"DARK_OAK_DOOR_BLOCK",      type:"block", textures:{0:"door_dark_oak_lower",1:"door_dark_oak_upper"} },

  // ==================== ITEMS ====================
  { id:256, material:"IRON_SPADE",               type:"item",  textures:{0:"iron_shovel"} },
  { id:257, material:"IRON_PICKAXE",             type:"item",  textures:{0:"iron_pickaxe"} },
  { id:258, material:"IRON_AXE",                 type:"item",  textures:{0:"iron_axe"} },
  { id:259, material:"FLINT_AND_STEEL",          type:"item",  textures:{0:"flint_and_steel"} },
  { id:260, material:"APPLE",                    type:"item",  textures:{0:"apple"} },
  { id:261, material:"BOW",                      type:"item",  textures:{0:"bow_standby"} },
  { id:262, material:"ARROW",                    type:"item",  textures:{0:"arrow"} },
  { id:263, material:"COAL",                     type:"item",  textures:{0:"coal",1:"charcoal"} },
  { id:264, material:"DIAMOND",                  type:"item",  textures:{0:"diamond"} },
  { id:265, material:"IRON_INGOT",               type:"item",  textures:{0:"iron_ingot"} },
  { id:266, material:"GOLD_INGOT",               type:"item",  textures:{0:"gold_ingot"} },
  { id:267, material:"IRON_SWORD",               type:"item",  textures:{0:"iron_sword"} },
  { id:268, material:"WOOD_SWORD",               type:"item",  textures:{0:"wood_sword"} },
  { id:269, material:"WOOD_SPADE",               type:"item",  textures:{0:"wood_shovel"} },
  { id:270, material:"WOOD_PICKAXE",             type:"item",  textures:{0:"wood_pickaxe"} },
  { id:271, material:"WOOD_AXE",                 type:"item",  textures:{0:"wood_axe"} },
  { id:272, material:"STONE_SWORD",              type:"item",  textures:{0:"stone_sword"} },
  { id:273, material:"STONE_SPADE",              type:"item",  textures:{0:"stone_shovel"} },
  { id:274, material:"STONE_PICKAXE",            type:"item",  textures:{0:"stone_pickaxe"} },
  { id:275, material:"STONE_AXE",                type:"item",  textures:{0:"stone_axe"} },
  { id:276, material:"DIAMOND_SWORD",            type:"item",  textures:{0:"diamond_sword"} },
  { id:277, material:"DIAMOND_SPADE",            type:"item",  textures:{0:"diamond_shovel"} },
  { id:278, material:"DIAMOND_PICKAXE",          type:"item",  textures:{0:"diamond_pickaxe"} },
  { id:279, material:"DIAMOND_AXE",              type:"item",  textures:{0:"diamond_axe"} },
  { id:280, material:"STICK",                    type:"item",  textures:{0:"stick"} },
  { id:281, material:"BOWL",                     type:"item",  textures:{0:"bowl"} },
  { id:282, material:"MUSHROOM_SOUP",            type:"item",  textures:{0:"mushroom_stew"} },
  { id:283, material:"GOLD_SWORD",               type:"item",  textures:{0:"gold_sword"} },
  { id:284, material:"GOLD_SPADE",               type:"item",  textures:{0:"gold_shovel"} },
  { id:285, material:"GOLD_PICKAXE",             type:"item",  textures:{0:"gold_pickaxe"} },
  { id:286, material:"GOLD_AXE",                 type:"item",  textures:{0:"gold_axe"} },
  { id:287, material:"STRING",                   type:"item",  textures:{0:"string"} },
  { id:288, material:"FEATHER",                  type:"item",  textures:{0:"feather"} },
  { id:289, material:"SULPHUR",                  type:"item",  textures:{0:"gunpowder"} },
  { id:290, material:"WOOD_HOE",                 type:"item",  textures:{0:"wood_hoe"} },
  { id:291, material:"STONE_HOE",                type:"item",  textures:{0:"stone_hoe"} },
  { id:292, material:"IRON_HOE",                 type:"item",  textures:{0:"iron_hoe"} },
  { id:293, material:"DIAMOND_HOE",              type:"item",  textures:{0:"diamond_hoe"} },
  { id:294, material:"GOLD_HOE",                 type:"item",  textures:{0:"gold_hoe"} },
  { id:295, material:"SEEDS",                    type:"item",  textures:{0:"seeds_wheat"} },
  { id:296, material:"WHEAT",                    type:"item",  textures:{0:"wheat"} },
  { id:297, material:"BREAD",                    type:"item",  textures:{0:"bread"} },
  { id:298, material:"LEATHER_HELMET",           type:"item",  textures:{0:"leather_helmet"} },
  { id:299, material:"LEATHER_CHESTPLATE",       type:"item",  textures:{0:"leather_chestplate"} },
  { id:300, material:"LEATHER_LEGGINGS",         type:"item",  textures:{0:"leather_leggings"} },
  { id:301, material:"LEATHER_BOOTS",            type:"item",  textures:{0:"leather_boots"} },
  { id:302, material:"CHAINMAIL_HELMET",         type:"item",  textures:{0:"chainmail_helmet"} },
  { id:303, material:"CHAINMAIL_CHESTPLATE",     type:"item",  textures:{0:"chainmail_chestplate"} },
  { id:304, material:"CHAINMAIL_LEGGINGS",       type:"item",  textures:{0:"chainmail_leggings"} },
  { id:305, material:"CHAINMAIL_BOOTS",          type:"item",  textures:{0:"chainmail_boots"} },
  { id:306, material:"IRON_HELMET",              type:"item",  textures:{0:"iron_helmet"} },
  { id:307, material:"IRON_CHESTPLATE",          type:"item",  textures:{0:"iron_chestplate"} },
  { id:308, material:"IRON_LEGGINGS",            type:"item",  textures:{0:"iron_leggings"} },
  { id:309, material:"IRON_BOOTS",               type:"item",  textures:{0:"iron_boots"} },
  { id:310, material:"DIAMOND_HELMET",           type:"item",  textures:{0:"diamond_helmet"} },
  { id:311, material:"DIAMOND_CHESTPLATE",       type:"item",  textures:{0:"diamond_chestplate"} },
  { id:312, material:"DIAMOND_LEGGINGS",         type:"item",  textures:{0:"diamond_leggings"} },
  { id:313, material:"DIAMOND_BOOTS",            type:"item",  textures:{0:"diamond_boots"} },
  { id:314, material:"GOLD_HELMET",              type:"item",  textures:{0:"gold_helmet"} },
  { id:315, material:"GOLD_CHESTPLATE",          type:"item",  textures:{0:"gold_chestplate"} },
  { id:316, material:"GOLD_LEGGINGS",            type:"item",  textures:{0:"gold_leggings"} },
  { id:317, material:"GOLD_BOOTS",               type:"item",  textures:{0:"gold_boots"} },
  { id:318, material:"FLINT",                    type:"item",  textures:{0:"flint"} },
  { id:319, material:"PORK",                     type:"item",  textures:{0:"porkchop_raw"} },
  { id:320, material:"GRILLED_PORK",             type:"item",  textures:{0:"porkchop_cooked"} },
  { id:321, material:"PAINTING",                 type:"item",  textures:{0:"painting_back"} },
  { id:322, material:"GOLDEN_APPLE",             type:"item",  textures:{0:"apple_golden",1:"apple_golden"} },
  { id:323, material:"SIGN",                     type:"item",  textures:{0:"sign"} },
  { id:324, material:"WOOD_DOOR",                type:"item",  textures:{0:"door_wood_lower"} },
  { id:325, material:"BUCKET",                   type:"item",  textures:{0:"bucket_empty"} },
  { id:326, material:"WATER_BUCKET",             type:"item",  textures:{0:"bucket_water"} },
  { id:327, material:"LAVA_BUCKET",              type:"item",  textures:{0:"bucket_lava"} },
  { id:328, material:"MINECART",                 type:"item",  textures:{0:"minecart_normal"} },
  { id:329, material:"SADDLE",                   type:"item",  textures:{0:"saddle"} },
  { id:330, material:"IRON_DOOR",                type:"item",  textures:{0:"door_iron_lower"} },
  { id:331, material:"REDSTONE",                 type:"item",  textures:{0:"redstone_dust"} },
  { id:332, material:"SNOW_BALL",                type:"item",  textures:{0:"snowball"} },
  { id:333, material:"BOAT",                     type:"item",  textures:{0:"boat"} },
  { id:334, material:"LEATHER",                  type:"item",  textures:{0:"leather"} },
  { id:335, material:"MILK_BUCKET",              type:"item",  textures:{0:"bucket_milk"} },
  { id:336, material:"CLAY_BRICK",               type:"item",  textures:{0:"brick"} },
  { id:337, material:"CLAY_BALL",                type:"item",  textures:{0:"clay_ball"} },
  { id:338, material:"SUGAR_CANE",               type:"item",  textures:{0:"reeds"} },
  { id:339, material:"PAPER",                    type:"item",  textures:{0:"paper"} },
  { id:340, material:"BOOK",                     type:"item",  textures:{0:"book_normal"} },
  { id:341, material:"SLIME_BALL",               type:"item",  textures:{0:"slimeball"} },
  { id:342, material:"CHEST_MINECART",           type:"item",  textures:{0:"minecart_normal"} },
  { id:343, material:"FURNACE_MINECART",         type:"item",  textures:{0:"minecart_normal"} },
  { id:344, material:"EGG",                      type:"item",  textures:{0:"egg"} },
  { id:345, material:"COMPASS",                  type:"item",  textures:{0:"compass"} },
  { id:346, material:"FISHING_ROD",              type:"item",  textures:{0:"fishing_rod_uncast"} },
  { id:347, material:"WATCH",                    type:"item",  textures:{0:"clock"} },
  { id:348, material:"GLOWSTONE_DUST",           type:"item",  textures:{0:"glowstone_dust"} },
  { id:349, material:"RAW_FISH",                 type:"item",  textures:{0:"fish_cod_raw",1:"fish_salmon_raw",2:"fish_clownfish_raw",3:"fish_pufferfish_raw"} },
  { id:350, material:"COOKED_FISH",              type:"item",  textures:{0:"fish_cod_cooked",1:"fish_salmon_cooked"} },
  { id:351, material:"INK_SACK",                 type:"item",  textures:{0:"dye_powder_black",1:"dye_powder_red",2:"dye_powder_green",3:"dye_powder_brown",4:"dye_powder_blue",5:"dye_powder_purple",6:"dye_powder_cyan",7:"dye_powder_silver",8:"dye_powder_gray",9:"dye_powder_pink",10:"dye_powder_lime",11:"dye_powder_yellow",12:"dye_powder_light_blue",13:"dye_powder_magenta",14:"dye_powder_orange",15:"dye_powder_white"} },
  { id:352, material:"BONE",                     type:"item",  textures:{0:"bone"} },
  { id:353, material:"SUGAR",                    type:"item",  textures:{0:"sugar"} },
  { id:354, material:"CAKE",                     type:"item",  textures:{0:"cake"} },
  { id:355, material:"BED",                      type:"item",  textures:{0:"bed_feet_top"} },
  { id:356, material:"DIODE",                    type:"item",  textures:{0:"repeater_off"} },
  { id:357, material:"COOKIE",                   type:"item",  textures:{0:"cookie"} },
  { id:358, material:"MAP",                      type:"item",  textures:{0:"map_filled"} },
  { id:359, material:"SHEARS",                   type:"item",  textures:{0:"shears"} },
  { id:360, material:"MELON",                    type:"item",  textures:{0:"melon"} },
  { id:361, material:"PUMPKIN_SEEDS",            type:"item",  textures:{0:"seeds_pumpkin"} },
  { id:362, material:"MELON_SEEDS",              type:"item",  textures:{0:"seeds_melon"} },
  { id:363, material:"RAW_BEEF",                 type:"item",  textures:{0:"beef_raw"} },
  { id:364, material:"COOKED_BEEF",              type:"item",  textures:{0:"beef_cooked"} },
  { id:365, material:"RAW_CHICKEN",              type:"item",  textures:{0:"chicken_raw"} },
  { id:366, material:"COOKED_CHICKEN",           type:"item",  textures:{0:"chicken_cooked"} },
  { id:367, material:"ROTTEN_FLESH",             type:"item",  textures:{0:"rotten_flesh"} },
  { id:368, material:"ENDER_PEARL",              type:"item",  textures:{0:"ender_pearl"} },
  { id:369, material:"BLAZE_ROD",                type:"item",  textures:{0:"blaze_rod"} },
  { id:370, material:"GHAST_TEAR",               type:"item",  textures:{0:"ghast_tear"} },
  { id:371, material:"GOLD_NUGGET",              type:"item",  textures:{0:"gold_nugget"} },
  { id:372, material:"NETHER_STALK",             type:"item",  textures:{0:"nether_wart"} },
  { id:373, material:"POTION",                   type:"item",  textures:{0:"potion_bottle_drinkable"} },
  { id:374, material:"GLASS_BOTTLE",             type:"item",  textures:{0:"potion_bottle_empty"} },
  { id:375, material:"SPIDER_EYE",               type:"item",  textures:{0:"spider_eye"} },
  { id:376, material:"FERMENTED_SPIDER_EYE",     type:"item",  textures:{0:"spider_eye_fermented"} },
  { id:377, material:"BLAZE_POWDER",             type:"item",  textures:{0:"blaze_powder"} },
  { id:378, material:"MAGMA_CREAM",              type:"item",  textures:{0:"magma_cream"} },
  { id:379, material:"BREWING_STAND_ITEM",       type:"item",  textures:{0:"brewing_stand"} },
  { id:380, material:"CAULDRON_ITEM",            type:"item",  textures:{0:"cauldron_side"} },
  { id:381, material:"EYE_OF_ENDER",             type:"item",  textures:{0:"ender_eye"} },
  { id:382, material:"SPECKLED_MELON",           type:"item",  textures:{0:"melon_speckled"} },
  { id:383, material:"MONSTER_EGG",              type:"item",  textures:{0:"spawn_egg"} },
  { id:384, material:"EXP_BOTTLE",               type:"item",  textures:{0:"experience_bottle"} },
  { id:385, material:"FIREBALL",                 type:"item",  textures:{0:"fire_charge"} },
  { id:386, material:"BOOK_AND_QUILL",           type:"item",  textures:{0:"book_writable"} },
  { id:387, material:"WRITTEN_BOOK",             type:"item",  textures:{0:"book_written"} },
  { id:388, material:"EMERALD",                  type:"item",  textures:{0:"emerald"} },
  { id:389, material:"ITEM_FRAME",               type:"item",  textures:{0:"item_frame"} },
  { id:390, material:"FLOWER_POT_ITEM",          type:"item",  textures:{0:"flower_pot"} },
  { id:391, material:"CARROT_ITEM",              type:"item",  textures:{0:"carrot"} },
  { id:392, material:"POTATO_ITEM",              type:"item",  textures:{0:"potato"} },
  { id:393, material:"BAKED_POTATO",             type:"item",  textures:{0:"potato_baked"} },
  { id:394, material:"POISONOUS_POTATO",         type:"item",  textures:{0:"potato_poisonous"} },
  { id:395, material:"EMPTY_MAP",                type:"item",  textures:{0:"map_empty"} },
  { id:396, material:"GOLDEN_CARROT",            type:"item",  textures:{0:"carrot_golden"} },
  //{ id:397, material:"SKULL_ITEM",               type:"item",  textures:{0:"skull_skeleton",1:"skull_wither",2:"skull_zombie",3:"skull_char",4:"skull_creeper"} },
  { id:398, material:"CARROT_STICK",             type:"item",  textures:{0:"carrot_on_a_stick"} },
  { id:399, material:"NETHER_STAR",              type:"item",  textures:{0:"nether_star"} },
  { id:400, material:"PUMPKIN_PIE",              type:"item",  textures:{0:"pumpkin_pie"} },
  { id:401, material:"FIREWORK",                 type:"item",  textures:{0:"fireworks"} },
  { id:402, material:"FIREWORK_CHARGE",          type:"item",  textures:{0:"fireworks_charge"} },
  { id:403, material:"ENCHANTED_BOOK",           type:"item",  textures:{0:"book_enchanted"} },
  { id:404, material:"REDSTONE_COMPARATOR",      type:"item",  textures:{0:"comparator_off"} },
  { id:405, material:"NETHER_BRICK_ITEM",        type:"item",  textures:{0:"nether_brick"} },
  { id:406, material:"QUARTZ",                   type:"item",  textures:{0:"quartz"} },
  { id:407, material:"TNT_MINECART",             type:"item",  textures:{0:"minecart_normal"} },
  { id:408, material:"HOPPER_MINECART",          type:"item",  textures:{0:"minecart_normal"} },
  { id:409, material:"PRISMARINE_SHARD",         type:"item",  textures:{0:"prismarine_shard"} },
  { id:410, material:"PRISMARINE_CRYSTALS",      type:"item",  textures:{0:"prismarine_crystals"} },
  { id:411, material:"RABBIT",                   type:"item",  textures:{0:"rabbit_raw"} },
  { id:412, material:"COOKED_RABBIT",            type:"item",  textures:{0:"rabbit_cooked"} },
  { id:413, material:"RABBIT_STEW",              type:"item",  textures:{0:"rabbit_stew"} },
  { id:414, material:"RABBIT_FOOT",              type:"item",  textures:{0:"rabbit_foot"} },
  { id:415, material:"RABBIT_HIDE",              type:"item",  textures:{0:"rabbit_hide"} },
  { id:416, material:"ARMOR_STAND",              type:"item",  textures:{0:"armor_stand"} },
  { id:417, material:"IRON_BARDING",             type:"item",  textures:{0:"horse_armor_iron"} },
  { id:418, material:"GOLD_BARDING",             type:"item",  textures:{0:"horse_armor_gold"} },
  { id:419, material:"DIAMOND_BARDING",          type:"item",  textures:{0:"horse_armor_diamond"} },
  { id:420, material:"LEASH",                    type:"item",  textures:{0:"lead"} },
  { id:421, material:"NAME_TAG",                 type:"item",  textures:{0:"name_tag"} },
  { id:422, material:"COMMAND_MINECART",         type:"item",  textures:{0:"minecart_normal"} },
  { id:423, material:"MUTTON",                   type:"item",  textures:{0:"mutton_raw"} },
  { id:424, material:"COOKED_MUTTON",            type:"item",  textures:{0:"mutton_cooked"} },
  { id:425, material:"BANNER",                   type:"item",  textures:{0:"banner_base"} },
  { id:427, material:"SPRUCE_DOOR_ITEM",         type:"item",  textures:{0:"door_spruce_lower"} },
  { id:428, material:"BIRCH_DOOR_ITEM",          type:"item",  textures:{0:"door_birch_lower"} },
  { id:429, material:"JUNGLE_DOOR_ITEM",         type:"item",  textures:{0:"door_jungle_lower"} },
  { id:430, material:"ACACIA_DOOR_ITEM",         type:"item",  textures:{0:"door_acacia_lower"} },
  { id:431, material:"DARK_OAK_DOOR_ITEM",       type:"item",  textures:{0:"door_dark_oak_lower"} },
];

export function getTextureById(id, meta) {
  const item = MC18_ITEMS.find(i => i.id === id);
  if (!item) return { error: "id nao encontrado" };

  const textureName = item.textures[meta || 0];
  if (!textureName) return { error: "meta invalida" };

  return {
    success: true,
    url: `https://raw.githubusercontent.com/PrismarineJS/minecraft-assets/master/data/1.8.8/${item.type}s/${textureName}.png`
  };
}

export function getTexture(material, metadata) {
  const item = MC18_ITEMS.find(function(i) { return i.material === material; });

  if (!item) return { error: 'Material "' + material + '" nao encontrado.' };

  const textureName = item.textures[metadata];
         
  if (!textureName) return { error: 'Metadata ' + metadata + ' nao existe para ' + material + '.' };

  const url = 'https://raw.githubusercontent.com/PrismarineJS/minecraft-assets/master/data/1.8.8/' + item.type + 's/' + textureName + '.png';

  return {
    success: true,
    type: item.type,
    material: material,
    metadata: metadata,
    texture: textureName,
    url: url
  };
}

const JULIA_TEXTURE_PATH = '/canary-wiki/julia-texture/';

const NORMALIZE_FOR_COMPARE = (str) => {
  if (!str) return '';
  return str
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/§k/g, '')
      .replace(/§[0-9a-f]/g, '')
      .replace(/§/g, '')
      .replace(/\s+/g, '-');
};

export function getJuliaTexture(displayName) {
  if (!displayName) return null;

  const cleanName = NORMALIZE_FOR_COMPARE(displayName);
  const url = JULIA_TEXTURE_PATH + cleanName + '.png';

  return {
    success: true,
    url: url,
    isLocal: true
  };
}

const textureCache = new Map();

export function getTextureWithFallback(id, meta = 0, displayName) {
  const key = `${id}-${meta}-${displayName || ''}`;

  if (textureCache.has(key)) return textureCache.get(key);

  const mc = getTextureById(id, meta);

  let primary = null;
  let fallback = mc.success ? mc.url : null;

  if (displayName) {
    let cleanName = NORMALIZE_FOR_COMPARE(displayName);

    if (cleanName.startsWith("livro-de")) cleanName = cleanName.replace(/-[ivxlcdm]+$/i, '')

    primary = JULIA_TEXTURE_PATH + cleanName + '.png';
  }

  if (mc.success) {
    fallback = mc.url;
    if (!primary) primary = mc.url;
  }

  const result = {
    primary: primary || fallback,
    fallback: fallback,
    success: !!(primary || fallback),
    url: primary || fallback
  };

  textureCache.set(key, result);
  return result;
}